[package]
name = "oxide"
version = "0.1.0"
edition = "2024"
license = "MIT"

[[bin]]
name = "ox"
path = "src/main.rs"

[dependencies]
ratatui = "0.29"
crossterm = "0.28"
thiserror = "2"
chrono = "0.4.43"
syntect = "5.3"
semver = "1"
ureq = "2"
serde_json = "1"

[dev-dependencies]
tempfile = "3"
